# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

      - save_cache:
          paths:
            - build
          key: v1-build-{{ .Revision }}

      - store_artifacts:
          path: build
  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-build-{{ .Revision }}
      - run: echo $DEPLOY_HOST_FINGERPRINT >> ~/.ssh/known_hosts
      - run: VERSION=$CIRCLE_SHA1 ENVIRONMENT=prod ./deploy.sh
  deploy_gcloud:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-build-{{ .Revision }}
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gsutil rsync -Rd build gs://onionsweeper/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  build_and_deploy_gcloud:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: gcloud
