# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

      - store_artifacts:
        path: build

      - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo $DEPLOY_HOST_FINGERPRINT >> ~/.ssh/known_hosts
            ./deploy.sh
          fi
